import {
  Cultivo,
  Planta,
  Registro,
  Tarea,
  Foto,
  Evento,
  Achievement,
  FertilizationLog,
  UserLearningProgress,
} from "./types";

export const initialCultivo: Cultivo = {
  id: "cultivo-1",
  name: "Cultivo Indoor Primavera 2026",
  startDate: "2026-07-15",
  status: "activo",
  stage: "Vegetativo",
  description: "Seguimiento botánico en interior optimizado con iluminación LED full spectrum y sustrato orgánico aireado.",
  method: "Indoor (Carpa)",
  space: "80x80x160 cm — Macetas Geotextiles 11L",
  image: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=1000&q=80",
  geneticName: "Aura Verde #4",
  geneticType: "Fotoperiódica",
  geneticOrigin: "Banco Seleccionado - Cruza Botánica",
  notes: "Foco en entrenamiento de bajo estrés (LST) y estabilidad de temperatura diurna entre 23°C y 25°C.",
  dates: {
    startDate: "2026-07-15",
    germinationDate: "2026-07-16",
    plantAddedDate: "2026-07-18",
    vegetativeStartDate: "2026-07-25",
    floweringStartDate: "2026-08-28",
    estimatedHarvestDate: "2026-10-25",
  },
  customStages: [
    { id: "stg-1", name: "Germinación", startDate: "2026-07-15", durationDays: 10, order: 1 },
    { id: "stg-2", name: "Vegetativo", startDate: "2026-07-25", durationDays: 34, order: 2, isCurrent: true },
    { id: "stg-3", name: "Floración", startDate: "2026-08-28", durationDays: 58, order: 3 },
    { id: "stg-4", name: "Lavado", startDate: "2026-10-18", durationDays: 7, order: 4 },
    { id: "stg-5", name: "Cosecha & Secado", startDate: "2026-10-25", durationDays: 14, order: 5 },
    { id: "stg-6", name: "Curado", startDate: "2026-11-08", durationDays: 30, order: 6 },
  ],
};

export const initialPlantas: Planta[] = [
  {
    id: "planta-1",
    cultivoId: "cultivo-1",
    name: "Aurora #01 (LST)",
    dateAdded: "2026-07-18",
    stage: "Vegetativo",
    status: "Óptimo",
    image: "https://images.unsplash.com/photo-1530968033775-2c92736b131e?auto=format&fit=crop&w=800&q=80",
    heightCm: 38.5,
    potSize: "11L Geotextil",
    notes: "Estructura vigorosa con 8 brotes principales tras la técnica LST.",
  },
  {
    id: "planta-2",
    cultivoId: "cultivo-1",
    name: "Brisa #02 (Apical)",
    dateAdded: "2026-07-18",
    stage: "Vegetativo",
    status: "Óptimo",
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80",
    heightCm: 42.0,
    potSize: "11L Geotextil",
    notes: "Poda apical realizada en día 21. Crecimiento simétrico y parejo.",
  },
  {
    id: "planta-3",
    cultivoId: "cultivo-1",
    name: "Solaria #03 (Control)",
    dateAdded: "2026-07-18",
    stage: "Vegetativo",
    status: "En observación",
    image: "https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&w=800&q=80",
    heightCm: 35.0,
    potSize: "11L Geotextil",
    notes: "Leve retraso en altura respecto a las hermanas; follaje sano y turgente.",
  },
];

export const initialRegistros: Registro[] = [
  {
    id: "reg-1",
    cultivoId: "cultivo-1",
    plantaId: "planta-1",
    date: "2026-08-18T10:30:00Z",
    temperature: 24.2,
    humidity: 62,
    watering: {
      performed: true,
      amountLiters: 1.5,
      volumeMl: 1500,
      ph: 6.3,
      ec: 1.2,
      nutrients: "Top Veg (2 ml/L) + Deeper Underground (1 ml/L)",
    },
    notes: "Riego suave matutino con drenaje del 10%. Las copas responden con excelente apertura hacia el panel LED.",
    images: [
      "https://images.unsplash.com/photo-1530968033775-2c92736b131e?auto=format&fit=crop&w=800&q=80",
    ],
    tags: ["riego", "ambiente", "crecimiento", "fertilizacion"],
  },
  {
    id: "reg-2",
    cultivoId: "cultivo-1",
    plantaId: "planta-2",
    date: "2026-08-17T18:00:00Z",
    temperature: 24.8,
    humidity: 59,
    notes: "Ajuste de tensores LST en ramas laterales. Follaje verde intenso y brillante.",
    images: [
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80",
    ],
    tags: ["mantenimiento", "crecimiento", "fotografia"],
  },
  {
    id: "reg-3",
    cultivoId: "cultivo-1",
    date: "2026-08-16T12:00:00Z",
    temperature: 23.9,
    humidity: 65,
    watering: {
      performed: true,
      amountLiters: 1.2,
      volumeMl: 1200,
      ph: 6.4,
      ec: 0.4,
      nutrients: "Solo agua reposada",
    },
    notes: "Riego de mantenimiento solo agua. Monitoreo ambiental en rango ideal de VPD.",
    images: [],
    tags: ["riego", "ambiente"],
  },
];

export const initialFertilizationLogs: FertilizationLog[] = [
  {
    id: "fert-1",
    cultivoId: "cultivo-1",
    plantaId: "planta-1",
    date: "2026-08-18",
    productId: "top_veg",
    productName: "Top Veg",
    volumeWaterLiters: 1.5,
    doseMlPerL: 2,
    totalProductMl: 3.0,
    stage: "Vegetativo",
    notes: "Aplicación semanal de crecimiento según tabla oficial Top Crop.",
  },
  {
    id: "fert-2",
    cultivoId: "cultivo-1",
    plantaId: "planta-1",
    date: "2026-08-18",
    productId: "deeper_underground",
    productName: "Deeper Underground",
    volumeWaterLiters: 1.5,
    doseMlPerL: 1,
    totalProductMl: 1.5,
    stage: "Vegetativo",
    notes: "Refuerzo radicular preventivo.",
  },
  {
    id: "fert-3",
    cultivoId: "cultivo-1",
    date: "2026-08-11",
    productId: "top_veg",
    productName: "Top Veg",
    volumeWaterLiters: 3.0,
    doseMlPerL: 2,
    totalProductMl: 6.0,
    stage: "Vegetativo",
    notes: "Fertirriego general para todo el cultivo.",
  },
  {
    id: "fert-4",
    cultivoId: "cultivo-1",
    date: "2026-08-04",
    productId: "barrier",
    productName: "Barrier",
    volumeWaterLiters: 3.0,
    doseMlPerL: 0.5,
    totalProductMl: 1.5,
    stage: "Vegetativo",
    notes: "Aporte de silicio para engrosar tallos y resistencia térmica.",
  },
];

export const initialTareas: Tarea[] = [
  {
    id: "task-1",
    cultivoId: "cultivo-1",
    title: "Medir pH y EC del drenaje",
    date: "2026-08-19",
    time: "10:00",
    repeat: "cada_2_dias",
    priority: "alta",
    completed: false,
    notes: "Asegurar que la acumulación de sales en maceta no supere 1.8 mS/cm.",
  },
  {
    id: "task-2",
    cultivoId: "cultivo-1",
    title: "Fertilización semanal: Top Veg (2-3 ml/L)",
    date: "2026-08-25",
    repeat: "semanal",
    priority: "alta",
    completed: false,
    isNutritionTask: true,
    notes: "Semana 4 de vegetativo. Preparar 3L de agua desclorada.",
  },
  {
    id: "task-3",
    cultivoId: "cultivo-1",
    title: "Inspección de envés de hojas con lupa 60x",
    date: "2026-08-20",
    repeat: "semanal",
    priority: "media",
    completed: false,
    notes: "Control biológico preventivo de trips y araña roja.",
  },
  {
    id: "task-4",
    cultivoId: "cultivo-1",
    title: "Cambio de fotoperiodo a 12/12 (Floración)",
    date: "2026-08-28",
    repeat: "ninguna",
    priority: "alta",
    completed: false,
    notes: "Programar temporizador de lámpara LED para inducir floración.",
  },
];

export const initialFotos: Foto[] = [
  {
    id: "foto-1",
    cultivoId: "cultivo-1",
    plantaId: "planta-1",
    date: "2026-08-18",
    cropDay: 35,
    image: "https://images.unsplash.com/photo-1530968033775-2c92736b131e?auto=format&fit=crop&w=800&q=80",
    stage: "Vegetativo",
    notes: "Día 35: Ramificación lateral excelente tras la guía LST.",
    tags: ["planta-1", "lst", "vegetativo"],
  },
  {
    id: "foto-2",
    cultivoId: "cultivo-1",
    plantaId: "planta-2",
    date: "2026-08-15",
    cropDay: 32,
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80",
    stage: "Vegetativo",
    notes: "Día 32: Cicatrización perfecta de poda apical y brotes secundarios simétricos.",
    tags: ["planta-2", "apical"],
  },
  {
    id: "foto-3",
    cultivoId: "cultivo-1",
    date: "2026-08-05",
    cropDay: 22,
    image: "https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&w=800&q=80",
    stage: "Vegetativo",
    notes: "Día 22: Vista general de la canopia.",
    tags: ["general", "canopia"],
  },
];

export const initialEventos: Evento[] = [
  {
    id: "evt-1",
    cultivoId: "cultivo-1",
    date: "2026-07-15",
    title: "Inicio del Cultivo e Hidratación de Semillas",
    description: "Siembra de semillas en jiffy y primer riego con Deeper Underground.",
    type: "hito",
  },
  {
    id: "evt-2",
    cultivoId: "cultivo-1",
    date: "2026-07-25",
    title: "Trasplante a Macetas Definitivas 11L",
    description: "Inoculación de sustrato con Micro Vita (micorrizas y trichodermas).",
    type: "trasplante",
  },
  {
    id: "evt-3",
    cultivoId: "cultivo-1",
    plantaId: "planta-2",
    date: "2026-08-05",
    title: "Poda Apical en Brisa #02",
    description: "Corte limpio por encima del 4to nudo.",
    type: "poda",
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: "ach-1",
    title: "Primer Brote",
    description: "Registra tu primer cultivo con éxito en Cultiva.",
    icon: "🌱",
    unlocked: true,
    unlockedAt: "2026-07-15",
  },
  {
    id: "ach-2",
    title: "Alquimista del pH",
    description: "Mide y registra el pH en más de 5 riegos consecutivos.",
    icon: "💧",
    unlocked: true,
    unlockedAt: "2026-08-10",
  },
  {
    id: "ach-3",
    title: "Nutricionista Botánico",
    description: "Consulta la tabla oficial Top Crop y registra una fertilización precisa.",
    icon: "🧪",
    unlocked: true,
    unlockedAt: "2026-08-18",
  },
  {
    id: "ach-4",
    title: "Estudiante Constante",
    description: "Lee al menos 3 artículos completos en la Enciclopedia de Autocultivo.",
    icon: "📚",
    unlocked: true,
    unlockedAt: "2026-08-18",
  },
  {
    id: "ach-5",
    title: "Fotógrafo de Tricomas",
    description: "Almacena 10 fotografías en la galería de evolución temporal.",
    icon: "📸",
    unlocked: false,
    progress: 3,
    maxProgress: 10,
  },
];

export const initialLearningProgress: UserLearningProgress = {
  readArticleIds: ["bio_ciclo_vida", "riego_ph_basico", "nut_ec_explicacion"],
  completedCategories: ["biologia", "riego"],
  currentLevel: "Principiante",
  favoriteArticleIds: ["riego_ph_basico", "amb_vpd_avanzado"],
  favoriteProductIds: ["top_veg", "top_candy", "deeper_underground"],
  favoriteSourceIds: ["src_top_crop_official", "src_fao"],
  favoriteLogIds: ["fert-1"],
  pendingArticleIds: ["sust_tierra_vs_coco", "desarrollo_podas_entrenamiento"],
};

export const mockArchivedCrop: Cultivo = {
  id: "cultivo-archived-1",
  name: "Cultivo Otoño 2025 (Concluido)",
  startDate: "2025-04-10",
  endDate: "2025-06-30",
  status: "archivado",
  stage: "Curado",
  description: "Ciclo fotoperiódico completo finalizado con 60 días de curado en frascos de vidrio herméticos.",
  method: "Indoor (Carpa)",
  space: "60x60x140 cm",
  image: "https://images.unsplash.com/photo-1528475478853-5b89bed65c4c?auto=format&fit=crop&w=800&q=80",
  yieldGrams: 145,
  rating: 5,
  notes: "Excelente rendimiento y aroma con el esquema Top Crop Tierra.",
};
